#!/usr/bin/env python3
"""修复 prompt 文件的内容质量问题"""

import os
import re
from pathlib import Path
from typing import Dict, Tuple

# 翻译和增强映射
FIXES = {
    # 占位符文件 - 写实/0026.md
    '/workspace/prompts/写实/0026.md': {
        'title_zh': 'AI视频模型技术对比测试',
        'title_en': 'AI Video Model Technical Comparison Test',
        'chinese': '''一场专业的AI视频生成模型技术对比实验，使用相同的参考图像和运动提示词进行严格测试。画面呈现多个分屏对比窗口，展示不同模型生成的视频片段同步播放，每个窗口标注模型名称、版本号和关键参数。背景是现代化的实验室环境，配备专业监视器阵列，柔和的工作室照明突出画面细节。画面以稳定的推拉镜头展现，专注于技术对比的精确性和专业性，4K高清分辨率，强调色彩一致性和运动流畅度的差异。''',
        'english': '''A professional technical comparison experiment of AI video generation models, conducting rigorous tests using identical reference images and motion prompts. The scene presents multiple split-screen comparison windows displaying synchronized playback of video clips generated by different models, each window labeled with model name, version number, and key parameters. The background features a modern laboratory environment equipped with professional monitor arrays, with soft studio lighting highlighting frame details. Captured with stable push-pull camera movement, focusing on the precision and professionalism of technical comparison, 4K high-definition resolution, emphasizing differences in color consistency and motion fluidity.'''
    },
    
    # 空内容文件 - 写实/0025.md
    '/workspace/prompts/写实/0025.md': {
        'title_zh': '摄影棚写实肖像',
        'title_en': 'Studio Photorealistic Portrait',
        'chinese': '''一位表情生动的人物肖像特写，专业摄影棚布光下的高品质拍摄。主体人物半身居中构图，眼神自然流露情感，细腻的皮肤质感和发丝细节清晰可见。使用三点式布光系统：主光从45度角柔和照射，营造立体面部轮廓；辅光填补阴影，保持细节；轮廓光勾勒边缘分离。背景采用渐变灰色无缝背景纸，景深控制使焦点精准落在人物面部。85mm定焦镜头拍摄，f/2.8光圈营造浅景深，色彩真实还原，展现专业人像摄影的技术标准和艺术美感。''',
        'english': '''A close-up portrait of a person with vivid expressions, captured in high quality under professional studio lighting. The subject is centered in a half-body composition, with natural eye contact conveying emotion, showcasing delicate skin texture and clearly visible hair details. Utilizing a three-point lighting system: key light softly illuminates from a 45-degree angle, creating three-dimensional facial contours; fill light balances shadows while preserving details; rim light outlines edges for separation. Background features gradient gray seamless backdrop paper, with depth of field control precisely focusing on the subject's face. Shot with 85mm prime lens at f/2.8 aperture for shallow depth of field, true-to-life color reproduction, demonstrating the technical standards and artistic aesthetics of professional portrait photography.'''
    }
}

# 常见的中英对照增强词汇库（用于丰富简短prompt）
ENRICHMENT_TEMPLATES = {
    'lighting': {
        'zh': ['柔和的自然光线', '戏剧性的侧光', '温暖的黄金时段光线', '柔和散射的光影', '明暗对比鲜明的光效'],
        'en': ['soft natural lighting', 'dramatic side lighting', 'warm golden hour light', 'soft diffused illumination', 'high-contrast lighting']
    },
    'camera': {
        'zh': ['稳定的跟踪镜头', '流畅的推拉运镜', '缓慢的环绕镜头', '低角度仰拍视角', '广角镜头展现空间感'],
        'en': ['steady tracking shot', 'smooth push-pull camera movement', 'slow orbiting shot', 'low-angle upward perspective', 'wide-angle lens capturing spatial depth']
    },
    'atmosphere': {
        'zh': ['充满动感的氛围', '宁静祥和的意境', '紧张刺激的气氛', '梦幻飘渺的质感', '史诗般宏大的气势'],
        'en': ['dynamic energetic atmosphere', 'serene peaceful ambiance', 'intense thrilling mood', 'dreamy ethereal quality', 'epic grand scale']
    }
}

def clean_footer(content: str) -> str:
    """移除页脚的整理行"""
    content = re.sub(r'\n整理：\[gentpan\]\(https://github\.com/gentpan\)\s*\n', '\n', content)
    content = re.sub(r'\n整理：\[Yep\].*?\n', '\n', content)
    content = re.sub(r'\n整理：Yep.*?\n', '\n', content)
    return content

def translate_to_chinese(english_text: str) -> str:
    """将英文prompt翻译成中文（简化版，实际使用规则映射）"""
    # 移除 [技术性 prompt，建议使用英文原文] 前缀
    english_text = re.sub(r'\[技术性 prompt[^]]*\]\s*', '', english_text)
    
    # 基础词汇映射
    translations = {
        # 摄影术语
        'cinematic': '电影感的',
        'photorealistic': '照片级真实的',
        'hyper-realistic': '超写实的',
        'shot': '镜头',
        'camera': '相机',
        'lens': '镜头',
        'perspective': '视角',
        'angle': '角度',
        'zoom in': '推进',
        'zoom out': '拉远',
        'crane shot': '摇臂镜头',
        'tracking shot': '跟踪镜头',
        'dolly': '移动镜头',
        'pan': '摇镜',
        'tilt': '俯仰',
        'close-up': '特写',
        'medium shot': '中景',
        'wide shot': '全景',
        'establishing shot': '定场镜头',
        
        # 光线
        'lighting': '光线',
        'natural light': '自然光',
        'soft light': '柔光',
        'hard light': '硬光',
        'golden hour': '黄金时段',
        'backlighting': '逆光',
        'rim light': '轮廓光',
        'ambient': '环境',
        'dramatic': '戏剧性的',
        
        # 运动
        'motion': '运动',
        'movement': '移动',
        'fast': '快速的',
        'slow': '缓慢的',
        'smooth': '流畅的',
        'dynamic': '动态的',
        'static': '静态的',
        'floating': '漂浮的',
        'flying': '飞行的',
        'running': '奔跑的',
        'walking': '行走的',
        
        # 环境
        'space': '空间',
        'galaxy': '星系',
        'planet': '行星',
        'stars': '星星',
        'cosmic': '宇宙的',
        'astronaut': '宇航员',
        'spacesuit': '太空服',
        'futuristic': '未来感的',
        'sci-fi': '科幻',
        
        # 质量
        'high quality': '高质量',
        '4K': '4K',
        '8K': '8K',
        'detailed': '细节丰富的',
        'sharp': '清晰的',
        'vibrant': '鲜艳的',
        'colorful': '色彩丰富的',
        
        # 其他
        'text': '文字',
        'your text here': '在此输入文字',
        'style': '风格',
        'scene': '场景',
        'background': '背景',
        'foreground': '前景',
        'atmosphere': '氛围',
        'mood': '情绪',
    }
    
    result = english_text
    for en, zh in translations.items():
        # 使用单词边界匹配，避免部分替换
        result = re.sub(r'\b' + re.escape(en) + r'\b', zh, result, flags=re.IGNORECASE)
    
    return result

def enrich_short_prompt(english_text: str, category: str) -> Tuple[str, str]:
    """增强过短的prompt，返回(中文, 英文)"""
    # 如果是相机指令类的技术prompt，添加场景化描述
    if 'crane' in english_text.lower() or 'zoom' in english_text.lower() or 'shot' in english_text.lower():
        if len(english_text) < 80:
            enriched_en = f"{english_text} Professional camera technique demonstration in a cinematic setting, showcasing smooth camera operation with precise timing and movement control. The scene features dynamic composition with careful attention to framing, maintaining visual interest throughout the motion. Shot with professional cinema camera equipment, maintaining consistent exposure and focus, demonstrating industry-standard cinematography practices."
            enriched_zh = translate_to_chinese(enriched_en)
            return enriched_zh, enriched_en
    
    # 对于风景、动作等类别，根据内容添加细节
    if category in ['风景', 'landscape']:
        enriched_en = f"{english_text} The landscape unfolds with rich atmospheric depth, featuring layered composition from foreground to distant horizon. Natural lighting enhances textures and colors, with careful attention to environmental details like vegetation, terrain, and sky. Captured with stable camera work emphasizing the scale and beauty of the natural environment, maintaining visual clarity and engaging perspective throughout."
    elif category in ['动作', 'action']:
        enriched_en = f"{english_text} Dynamic action sequence with precise choreography and impactful movement. The camera follows the action with energetic but controlled framing, maintaining subject clarity while conveying speed and intensity. Lighting emphasizes the dramatic nature of the movement, with careful attention to timing and spatial relationships for maximum visual impact."
    else:
        # 通用增强
        enriched_en = f"{english_text} The scene is crafted with cinematic attention to visual storytelling, featuring deliberate composition and lighting that enhances mood and atmosphere. Camera movement is purposeful and smooth, guiding viewer attention while maintaining engagement. Professional-grade visual quality with rich detail and coherent aesthetic throughout."
    
    enriched_zh = translate_to_chinese(enriched_en)
    return enriched_zh, enriched_en

def fix_file(filepath: Path) -> bool:
    """修复单个文件，返回是否有修改"""
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original_content = content
    modified = False
    
    # 1. 检查是否有预定义的完整替换
    if str(filepath) in FIXES:
        fix_data = FIXES[str(filepath)]
        # 更新标题
        content = re.sub(r'title_zh: .*', f"title_zh: {fix_data['title_zh']}", content)
        content = re.sub(r'title_en: .*', f"title_en: {fix_data['title_en']}", content)
        # 更新中文内容
        content = re.sub(
            r'(## 中文\n\n\*\*[^*]*\*\*\n\n).*?(?=\n## English)',
            r'\1' + fix_data['chinese'] + '\n',
            content,
            flags=re.DOTALL
        )
        # 更新英文内容
        content = re.sub(
            r'(## English\n\n\*\*[^*]*\*\*\n\n).*?(?=\n---)',
            r'\1' + fix_data['english'] + '\n',
            content,
            flags=re.DOTALL
        )
        modified = True
    else:
        # 2. 提取分类
        category_match = re.search(r'category: (\S+)', content)
        category = category_match.group(1) if category_match else ''
        
        # 3. 处理中文部分有英文的情况
        chinese_match = re.search(r'(## 中文\n\n\*\*[^*]*\*\*\n\n)(.*?)(?=\n## English)', content, re.DOTALL)
        if chinese_match:
            chinese_section = chinese_match.group(2).strip()
            # 移除 [技术性 prompt，建议使用英文原文] 标记
            if '[技术性 prompt' in chinese_section:
                # 找到对应的英文内容
                english_match = re.search(r'## English\n\n\*\*[^*]*\*\*\n\n(.*?)(?=\n---)', content, re.DOTALL)
                if english_match:
                    english_text = english_match.group(1).strip()
                    # 翻译英文到中文
                    translated_chinese = translate_to_chinese(english_text)
                    content = re.sub(
                        r'(## 中文\n\n\*\*[^*]*\*\*\n\n).*?(?=\n## English)',
                        r'\1' + translated_chinese + '\n',
                        content,
                        flags=re.DOTALL
                    )
                    modified = True
        
        # 4. 处理过短的prompt
        english_match = re.search(r'(## English\n\n\*\*[^*]*\*\*\n\n)(.*?)(?=\n---)', content, re.DOTALL)
        if english_match:
            english_section = english_match.group(2).strip()
            # 去掉可能的整理行
            english_lines = [l for l in english_section.split('\n') if not l.startswith('整理：')]
            english_text = ' '.join(english_lines).strip()
            
            if len(english_text) < 80:
                enriched_zh, enriched_en = enrich_short_prompt(english_text, category)
                # 更新英文
                content = re.sub(
                    r'(## English\n\n\*\*[^*]*\*\*\n\n).*?(?=\n---)',
                    r'\1' + enriched_en + '\n',
                    content,
                    flags=re.DOTALL
                )
                # 更新中文
                content = re.sub(
                    r'(## 中文\n\n\*\*[^*]*\*\*\n\n).*?(?=\n## English)',
                    r'\1' + enriched_zh + '\n',
                    content,
                    flags=re.DOTALL
                )
                modified = True
    
    # 5. 清理页脚
    cleaned = clean_footer(content)
    if cleaned != content:
        content = cleaned
        modified = True
    
    # 6. 写回文件
    if modified and content != original_content:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    
    return False

def main():
    # 读取分析结果，只修复有问题的文件
    problem_files = [
        '/workspace/prompts/其它/0001.md',
        '/workspace/prompts/其它/0009.md',
        '/workspace/prompts/写实/0003.md',
        '/workspace/prompts/写实/0006.md',
        '/workspace/prompts/写实/0007.md',
        '/workspace/prompts/写实/0008.md',
        '/workspace/prompts/写实/0010.md',
        '/workspace/prompts/写实/0011.md',
        '/workspace/prompts/写实/0014.md',
        '/workspace/prompts/写实/0015.md',
        '/workspace/prompts/写实/0017.md',
        '/workspace/prompts/写实/0018.md',
        '/workspace/prompts/写实/0020.md',
        '/workspace/prompts/写实/0021.md',
        '/workspace/prompts/写实/0023.md',
        '/workspace/prompts/写实/0025.md',
        '/workspace/prompts/写实/0026.md',
        '/workspace/prompts/写实/0029.md',
        '/workspace/prompts/写实/0032.md',
        '/workspace/prompts/动作/0003.md',
        '/workspace/prompts/动漫/0006.md',
        '/workspace/prompts/动漫/0010.md',
        '/workspace/prompts/动画/0002.md',
        '/workspace/prompts/动画/0003.md',
        '/workspace/prompts/动画/0005.md',
        '/workspace/prompts/动画/0010.md',
        '/workspace/prompts/动画/0013.md',
        '/workspace/prompts/动画/0014.md',
        '/workspace/prompts/动画/0017.md',
        '/workspace/prompts/动画/0019.md',
        '/workspace/prompts/奇幻/0001.md',
        '/workspace/prompts/奇幻/0002.md',
        '/workspace/prompts/奇幻/0003.md',
        '/workspace/prompts/奇幻/0004.md',
        '/workspace/prompts/奇幻/0005.md',
        '/workspace/prompts/奇幻/0006.md',
        '/workspace/prompts/奇幻/0008.md',
        '/workspace/prompts/奇幻/0009.md',
        '/workspace/prompts/抽象/0001.md',
        '/workspace/prompts/抽象/0004.md',
        '/workspace/prompts/抽象/0007.md',
        '/workspace/prompts/抽象/0008.md',
        '/workspace/prompts/电影/0003.md',
        '/workspace/prompts/电影/0005.md',
        '/workspace/prompts/电影/0008.md',
        '/workspace/prompts/电影/0012.md',
        '/workspace/prompts/电影/0029.md',
        '/workspace/prompts/电影/0031.md',
        '/workspace/prompts/科幻/0002.md',
        '/workspace/prompts/科幻/0003.md',
        '/workspace/prompts/科幻/0004.md',
        '/workspace/prompts/科幻/0005.md',
        '/workspace/prompts/科幻/0006.md',
        '/workspace/prompts/科幻/0007.md',
        '/workspace/prompts/科幻/0008.md',
        '/workspace/prompts/科幻/0009.md',
        '/workspace/prompts/编辑/0007.md',
        '/workspace/prompts/编辑/0012.md',
        '/workspace/prompts/视频/0001.md',
        '/workspace/prompts/视频/0005.md',
        '/workspace/prompts/视频/0006.md',
        '/workspace/prompts/视频/0007.md',
        '/workspace/prompts/视频/0008.md',
        '/workspace/prompts/视频/0009.md',
        '/workspace/prompts/视频/0011.md',
        '/workspace/prompts/视频/0013.md',
        '/workspace/prompts/视频/0014.md',
        '/workspace/prompts/视频/0015.md',
        '/workspace/prompts/视频/0016.md',
        '/workspace/prompts/视频/0019.md',
        '/workspace/prompts/视频/0021.md',
        '/workspace/prompts/视频/0022.md',
        '/workspace/prompts/视频/0024.md',
        '/workspace/prompts/视频/0025.md',
        '/workspace/prompts/风景/0001.md',
        '/workspace/prompts/风景/0003.md',
        '/workspace/prompts/风景/0004.md',
        '/workspace/prompts/风景/0005.md',
        '/workspace/prompts/风景/0006.md',
        '/workspace/prompts/风景/0012.md',
        '/workspace/prompts/风格/0003.md',
        '/workspace/prompts/风格/0006.md',
        '/workspace/prompts/风格/0007.md',
    ]
    
    fixed_count = 0
    for filepath_str in problem_files:
        filepath = Path(filepath_str)
        if filepath.exists():
            if fix_file(filepath):
                fixed_count += 1
                print(f"✓ 已修复: {filepath.name} ({filepath.parent.name})")
        else:
            print(f"✗ 文件不存在: {filepath}")
    
    print(f"\n总计修复 {fixed_count} / {len(problem_files)} 个文件")

if __name__ == '__main__':
    main()
